# Generated by Django 4.1.5 on 2023-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tag_post', to='blog.tags', verbose_name='теги'),
        ),
    ]
