# Generated by Django 4.1.5 on 2023-03-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='tread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tread_reviews', to='blog.reviews', verbose_name='Тред'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_reviews', to='blog.reviews', verbose_name='Родитель'),
        ),
    ]
