# Generated by Django 4.1.5 on 2023-04-03 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_reviews_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата нотификации')),
                ('is_prived', models.BooleanField(default=False, verbose_name='Приватная')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новая')),
                ('initializer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_initializer', to=settings.AUTH_USER_MODEL, verbose_name='Инициализатор')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to='blog.post', verbose_name='Пост')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_notification', to='blog.reviews', verbose_name='Ревью')),
            ],
        ),
    ]
