# Generated by Django 4.1.5 on 2023-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lp', 'Post Like'), ('f', 'Following'), ('rc', 'Review Creation'), ('rl', 'Review Like')], default='lp', max_length=2),
        ),
    ]
