# Generated by Django 4.1.5 on 2023-05-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lp', 'Post Like'), ('f', 'Following'), ('rc', 'Review Creation'), ('rl', 'Review Like'), ('no', 'None')], default='lp', max_length=2),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by_review', to='blog.post', verbose_name='Пост'),
        ),
    ]
